---
- name: Create haltode.fr directory
  file:
    name: "{{ haltode_fr_dir }}"
    state: directory

- name: Clone haltode.fr git repository
  git:
    repo: 'https://github.com/haltode/haltode.fr.git'
    dest: "{{ haltode_fr_dir }}"
    update: yes
    version: main

- name: Create haltode.fr virtualenv
  pip:
    name: pip
    virtualenv: "{{ haltode_fr_venv }}"
    virtualenv_command: /usr/bin/env python3 -m venv

- name: Setup haltode.fr virtualenv
  shell: |
    # Necessary manual steps to use the pyproject.toml setup file
    source "{{ haltode_fr_venv }}/bin/activate"
    python -m pip install --upgrade pip
    python -m pip install .
  args:
    executable: /bin/bash
    chdir: "{{ haltode_fr_dir }}"

- name: Build haltode.fr website
  shell: |
    source "{{ haltode_fr_venv }}/bin/activate"
    make build
    make collectstatic
  args:
    executable: /bin/bash
    chdir: "{{ haltode_fr_dir }}"
