---
- name: Install Jellyfin dependencies
  apt:
    name: apt-transport-https
    state: present

- name: Import Jellyfin GPG key
  apt_key:
    url: https://repo.jellyfin.org/debian/jellyfin_team.gpg.key
    state: present

- name: Add Jellyfin repository
  apt_repository:
    repo: deb https://repo.jellyfin.org/debian buster main
    state: present

- name: Install Jellyfin media system
  apt:
    update_cache: yes
    name: jellyfin
    state: present

- name: Reload Jellyfin
  service:
    name: jellyfin
    state: restarted
