---
- name: Install base packages used on keaton
  apt:
    name:
      - curl
      - fish
      - git
      - htop
      - postgresql
      - python3
      - python3-apt
      - python3-dev
      - python3-psycopg2
      - python3-venv
      - sudo
      - vim
    update_cache: yes

- name: Add haltode user
  user:
    name: haltode
    comment: Thibault Allançon
    shell: /bin/fish
    group: haltode
    groups:
      - haltode
      - users
      - sudo

- name: Add haltode postgresql user
  postgresql_user:
    name: haltode
    role_attr_flags: SUPERUSER,CREATEDB
  become: true
  become_user: postgres
