---
- name: Install base packages used on keaton
  apt:
    name:
      - curl
      - fish
      - git
      - htop
      - python3
      - python3-apt
      - python3-dev
      - python3-venv
      - sudo
      - vim
    update_cache: yes
