---
- name: Install base packages used on keaton
  apt:
    name:
      - curl
      - fish
      - git
      - htop
      - python3
      - python3-apt
      - python3-dev
      - python3-venv
      - sudo
      - vim
    update_cache: yes

- name: Add haltode user
  user:
    name: haltode
    comment: Thibault Allançon
    shell: /bin/fish
    group: haltode
    groups:
      - haltode
      - users
      - sudo
